server:
  port: 9081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
#    TODO url: "jdbc:postgresql://<postgres server connection URL>/<databasename>"
#    username: testname
#    password: testpassword
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        ddl-auto: update